# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbdc817901b915011b00bdef94f18c8c80153a10d71855cd7aea033faf9a17a9941e2cbc2c47f56a0e9250a1e2198bdcdb1ae109d21ddd4769db206f09c972f
  user: admin
  password: sjit

test:
  secret_key_base: e3e3a486e8afdc956a5a362c6c4e512b6f9e822f6c0d742a9fab13ded674581913531771345c4068e4746d427e98edb7227806e834f1731c64946976f62d515c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: <%= ENV["USER_NAME"] %>
  password: <%= ENV["USER_PASSWORD"] %>
